# environment-base.yml
name: SLI311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - blas=*=openblas
  - numpy
  - pandas
  - xarray
  - scipy
  - dask
  - seaborn
  - matplotlib        
  - ipykernel
  - ipywidgets
  - nbformat
  - notebook
  - netcdf4           
  - flox
  - utide
  - joblib
  - cartopy
  - geopandas
  - plotly
  - myst-nb
  - mpich
  - mpi4py
  - pip
  - pip:
      - pyextremes
      - great_tables
      - copernicusmarine
      - spotpy
      - selenium ## This one is only if you want to colorize your dataframes...
      